# Generated by Django 6.0.4 on 2026-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="budget_month",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
