# Generated by Django 6.0.4 on 2026-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_userprofile_budget_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_access_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_refresh_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
