# Generated by Django 6.0.4 on 2026-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_userprofile_google_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("transport", "Transport"),
                    ("shopping", "Shopping"),
                    ("health", "Health"),
                    ("entertainment", "Entertainment"),
                    ("bills", "Bills"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
