# Generated by Django 6.0.4 on 2026-05-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pending_oauth_state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_oauth_verifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
