# Generated by Django 6.0.7 on 2026-07-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_googleoauthstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="balance_setup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="budget_mode",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly Budget"),
                    ("balance", "Current Balance & Daily Limit"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fixed_daily_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
