# Generated by Django 6.1 on 2026-08-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0008_userprofile_balance_setup_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="google_access_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="google_refresh_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="google_token_expiry",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pending_oauth_state",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pending_oauth_verifier",
        ),
        migrations.DeleteModel(
            name="GoogleOAuthState",
        ),
    ]
