# Generated by Django 6.1 on 2026-09-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0010_monthlybudgethistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("dining", "Dining"),
                    ("groceries", "Groceries"),
                    ("housing", "Housing"),
                    ("transport", "Transport"),
                    ("shopping", "Shopping"),
                    ("health", "Health"),
                    ("entertainment", "Entertainment"),
                    ("bills", "Bills"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
